[project]
name = "app"
version = "0.1.0"
description = "My MCP tests"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litellm>=1.18.0",
    "mcp[cli]>=1.8.0",
    "prompt-toolkit>=3.0.51",
    "python-dotenv>=1.1.0",
]
